cask_args no_quarantine: true

brew "zsh"
brew "zsh-lovers"
brew "zsh-completions"
brew "bash"
brew "fzf"
brew "zoxide"
brew "vim"
brew "neovim"
brew "tree"
brew "ag"
brew "ispell"
brew "aspell"
brew "hunspell"
brew "graphviz"
brew "gcc"
brew "cloc"
brew "thefuck"
brew "fontconfig"
brew "coreutils"
brew "ssh-copy-id"
brew "git"
brew "mas"
brew "jq"
brew "htop"
brew "openssl"
brew "gh"
brew "bat"
brew "grep"
brew "gnu-sed"

brew "starship"

# cask "mailmate"
# cask "marta"
cask "raycast"
cask "launchbar"
cask "iterm2"
cask "spotify"
# cask "vivaldi"
# cask "firefox"
cask "jetbrains-toolbox"
cask "1password"
# cask "karabiner-elements"
cask "contexts"
cask "daisydisk"
cask "signal"
cask "visual-studio-code"

cask "font-victor-mono"
cask "font-victor-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "font-dejavu"
cask "font-dejavu-sans-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-latin-modern-math"
cask "font-stix-two-math"
cask "font-noto-color-emoji"
cask "font-noto-emoji"
cask "font-noto-sans"
cask "font-noto-sans-math"
cask "font-noto-sans-symbols"
cask "font-noto-sans-symbols-2"

brew "gnutls"
brew "jansson"
brew "libxml2"
brew "texinfo"
brew "imagemagick"

tap "d12frosted/emacs-plus"
brew "d12frosted/emacs-plus/emacs-plus@30", args: ["with-dbus", "with-debug", "with-imagemagick", "with-native-comp"]


brew "gpg"
brew "gawk"

brew "ranger"
brew "w3m"
brew "most"

cask "beyond-compare"

brew "languagetool"

brew "duf"
brew "httpie"
brew "ncdu"
brew "fx"
brew "lazydocker"
brew "glow"
brew "ki"

brew "sqlite"
brew "wordnet"
brew "proselint"

brew "aws-vault"
brew "awscli"
brew "localstack"
