#!/bin/zsh
# vim: set ft=zsh :

# Install sheldon
# Check if sheldon is installed
if (( ! $+commands[sheldon] )); then


  mkdir -p ~/.local/bin
  curl --proto '=https' -fLsS https://rossmacarthur.github.io/install/crate.sh \
    | bash -s -- --repo rossmacarthur/sheldon --to ~/.local/bin

fi
SCRIPT_DIR="${0:A:h}"
export SHELDON_CONFIG_DIR="${SCRIPT_DIR:A}/../sheldon"

# Start shell
eval "$(sheldon source)"
