#!/bin/zsh
# vim: set ft=zsh :
# Install zinit
# Check if zinit is installed
if [[ ! -d ~/.zinit ]]; then
  mkdir -p ~/.zinit
  git clone https://github.com/zdharma-continuum/zinit.git ~/.zinit/bin
  source ~/.zinit/bin/zinit.zsh & zinit self-update
fi

# Essential
source ~/.zinit/bin/zinit.zsh
