#!/bin/zsh
# vim: set ft=zsh :

zinit ice depth=1

zinit light jeffreytse/zsh-vi-mode

# I should probalby sort/break these apart
# turbo mode loading
zinit light-mode wait lucid for \
  zsh-users/zsh-completions \
  jreese/zsh-titles \
  laggardkernel/zsh-thefuck \
  hlissner/zsh-autopair \
  zpm-zsh/ls \
  marlonrichert/zsh-hist \
  b0o/zfzf \
  wfxr/forgit \

# Move to bottom, after starship - can cause issues where the prompt disappears
zplugin ice pick'init.zsh' compile'*.zsh'
zplugin light laggardkernel/zsh-iterm2
