# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

test -f ~/.zshrc_before && source ~/.zshrc_before

# shell and globbing options
set extended_glob
set numeric_glob_sort
set glob_dots
set nomatch

set autocd
set autopushd

export CDPATH=".:~"

set correct

# jobs
set notify

# TODO: these should literally all be plugins.  I've basically created my own janky ass plugin system as is.
# Source all files from .zsh.d, unless they contain ~ (assumes vim temp files)
for zshrc_config in ~/.zsh.d/*[^~] ; do
#  echo "Sourcing $zshrc_config"
  source $zshrc_config
done

fpath=(~/.zsh/completion $fpath)

# Add doom to path
export PATH="$HOME/.emacs.d/bin:$PATH"

# Source a local zshrc if found (though that is better managed with profiles)
test -f ~/.zshrc_local && source ~/.zshrc_local
